schema_version: 1

context:
  version: "0.2.3"

package:
  name: lsp-tree-sitter
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/lsp-tree-sitter/lsp_tree_sitter-${{ version }}.tar.gz
  sha256: aaa5445a41c7926c50fae15827f2dcaae838fa585da045c7b2644bff99bf5df0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python =${{ python_min }}
    - setuptools
    - setuptools-scm >=6.2
    - setuptools-generate >=0.0.6
    - pip
  run:
    - python >=${{ python_min }}
    - colorama
    - jinja2
    - jsonschema >=4.0.0
    - pygls
    - tree_sitter >=0.22.0

tests:
  - python:
      imports:
        - lsp_tree_sitter
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check

about:
  summary: A library to create language servers
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - template/LICENSE
  homepage: https://github.com/neomutt/lsp-tree-sitter
  repository: https://github.com/neomutt/lsp-tree-sitter

extra:
  recipe-maintainers:
    - danielnachun
